= asciiDoc 语法
:revnumber: 1.0
:revdate: 2020-10-29
:revremark: for a better world
:toc: left
:toc-title: asciiDoc学习
:author: 谢明辉
:email: zui19961102@gmail.com
// 在标题上添加锚点
:sectanchors:
// 节点编号
:sectnums:
:doctype: book
:table-stripes: hover
:example-caption!:
:table-caption!:

== 段落

文档中的大部分内容都是段落文本。这就是为什么Asciidoctor不需要任何特殊的标记或属性来指定段落内容的原因。您可以开始输入。

=== 正常

====
hello, what's your name?

good bye.
====

=== 换行

.换行符使用空格和(+)保留
====
hello, what's your name? +
good bye.
====

.使用[%hardbreaks]选项保留换行符
====
[%hardbreaks]
换行
换行
====

要在整个文档中保留换行符,需要将[%hardbreaks]属性添加到文档标题中

....
= Title
:hardbreaks:

something.......
....

=== 文字

====
A normal paragraph.

 hello, what's your name?
 good bye.

A normal paragraph.
====

=== 警告

====
NOTE: this is a note. +
this is a note.

TIP: this is a tip.

IMPORTANT: this is important.

WARNING: this is warning.

CAUTION: ha
====

=== 概要段落

====
[.lead]
This text will be styled as a lead paragraph (i.e., larger font).
====

=== 对准

提供了内置对准模式, 命名规则为 `[.text-<alignment>]`, `<alignment>` 为left, center, right和justify之一

====
[.text-center]
这是居中的段落
====

== 格式化文本

=== 基本

====
_斜体_ +
__斜__体体体体 +
*加粗* +
**加**粗粗粗粗 +
*_又粗又斜_* +
又**__粗__**又**__斜__** +
`等 距 短 语` 等``距````短``语 +
`*_来吧_*`,come on b``**__a__**``by let's go~!
====

=== 自定义样式

    #高亮#
    [small]##小一号##
    [big]##大一号##

====

你见过 #高亮# 的字吗 +
你见过 [small]##小一号## 的字吗 +
你见过 [big]##大一号## 的字吗

====

=== 角标

    ^上标^
    ~下标~

====

这是一个^上标^ +
这是一个~下标~

====

=== 引号

    '`引号`'
    "`双引号`"

====

'`引号`' +
"`双引号`" +

====

== 包含文件

    include::include1.adoc[]

====

include::include1.adoc[]

====

== 水平线

    '''
    ---
    ***
    - - -
    * * *

====
'''
---
***
- - -
* * *
====

== 列表

=== 无序列表

====

* 大
** 中
*** 小
**** 小小
* 再大

====

=== 清单

====

.普通
======
- [*] 完了
- [*] 完了
- [ ] 完蛋了
======

====

====

.可交互
======
[%interactive]
- [*] 土豆
- [*] 苹果
- [ ] 西红柿
======

====

=== 有序列表

====

.从某个顺序开始
======
[start=4]
. 苹果
. 香蕉
. 西红柿
======

====

====

.倒序
======
[%reversed]
. 苹果
. 香蕉
. 西葫芦
======

====

====

.带有标题的水果
======
.水果
. 苹果
. 香蕉
. 西瓜
======

====

=== 说明清单

====
// 使说明和内容显示在同一行
[horizontal]
中央处理器:: 计算机的大脑.
硬盘:: 操作系统和/或用户文件的永久存储.
内存:: 临时存储CPU在操作期间使用的信息.

====

=== 问答列表

====

[qanda]
什么是道?:: 道可道, 非常道.
What is the answer to the Ultimate Question?:: 42

====

== 块

=== 标题

您可以为任何段落，列表，定界块或块宏分配标题。在大多数情况下，标题会直接显示在内容上方。如果内容是图形或图像，则标题显示在内容下方。

块标题定义在元素上方的一行上。该行必须以点（`.`）开头，并紧随其后的是标题文本。

====

.标题是水果蔬菜
* 苹果
* 香蕉
* 西红柿

====

=== 元数据

====

除标题外还可以为块分配其他元数据,包括:

* ID(锚)
* 块名称
* 块属性

//标题
.Gettysburg Address
//ID, 锚
[#gettysburg]
// 块属性[块名:引用,人名:亚伯拉罕林肯,地址:葛底斯堡公墓专用地址]
[quote,Abraham Lincoln,Address delivered at the dedication of the Cemetery at Gettysburg]
____
Four score and seven years ago our fathers brought forth on this continent a new nation...

Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and so dedicated, can long endure.
...
____

====

=== 常用块定界符

[cols="^.^1h,2*^.^1l,1*.^4l"]
.块界定符表
|===
|块|块名|定界符|描述

|段落|||常规段落内容（即散文），在任一侧都用空白行偏移。必须开始平齐到文档的左边距。块名称可用于将段落转换为大多数其他块。
|文字段落|||用于文字内容（即，预格式化的文本）的特殊类型的段落块。必须从文档的左边缘缩进至少一个空格。当内容不包含任何空白行时，通常用作文字分隔块的简写形式。
|警告|[<LABEL>]|====|需要特别注意的内容,通常标有标签或图标
|注释||////|不用于显示的内容
|举例|[example]|====|指定实例内容或定义警告块
|围栏||```|完全按输入显示源代码
|Listing|[listing]|----|完全按输入显示源代码
|文字|[literal]|....|完全按输入显示
|Open|Most block names|--|可以用做除passThrough和table之外的任何块的匿名块
|直接输出|[pass]|++++|输出未经处理的内容
|引用|[quote]|____|带有属性的引用
|侧边栏|[sidebar]|****|除了文档流之外显示的文本和内容
|Stem|[stem]|++++|输出未经处理的内容
|Table||\|===|表格
|诗|[verse]|____|带有属性的诗句
|===

== 表格

由 `|===` 界定并创建表格, 每次遇到 `|` 都会创建一个单元格, 每行必须有相同数量的单元格

.简单表
....
|===

|一行一列|一行二列
|二行一列|二行二列

|===
....

=== 列

当一行的单元格连续输入时, 需要使用 `cols` 属性来指定表中的列数, 如果 `cols` 未设置的话,则以 `|===` 内的第一行非空白行确定列数

....
[cols="2*"] 2列
[cols="1,1"] 也是两列
....

=== 列格式

AsciiDoc提供了多种方法控制列中内容的大小, 样式和布局, 这些说明符可以应用于整列. +
要将说明符应用于列, 必须设置 `cols` 属性并为其分配值, 列说明符可以包含以下组件:

* multiplier
* align
* width
* style

如果要将说明符应用于多个连续的列, 可以使用 `*` .必须将其放在说明符之前.

==== 对齐组件

* `<` 左对齐
* `^` 居中
* `>` 右对齐
* `.<` 顶部对齐
* `.^` 垂直居中
* `.>` 底部对齐

.对齐
....
[cols="3*<.<"]
[cols="<,^,>"]
[cols=".<,.^,.>"]
[cols="2*,^.^"]
....

==== 列宽

宽度组件设置列的宽度,他的值可以是比例整数或百分比(1-99)

.宽度
....
[cols="1,2,3"]
[cols="2*2,5"]
[cols="50,20,30"]    百分比,无需 %
[cols="2*^.^2,<.^5,>.>4"] 具有对齐和宽度的列格式
....

==== 样式

.列样式表
[cols="2*^.^1,.^5",caption=]
|===
|样式名称|值|描述

|AsciiDoc|a|支持块级元素（段落，定界的块和块宏）.
|强调|e|斜体
|头部|h|头部样式应用于列
|文字|l|列文字被认为处于文字块内
|等宽|m|文本以等宽显示
|无|d|默认样式,像普通段落一样处理
|粗体|s|文字为粗体
|诗|v|列内容被视为诗句
|===

=== 单元格格式

就像列一样,单元格也可以通过说明符来改变样式:

* span
* align
* style

.单元格三列重复
====

    3*|举例

|===
3*|举例
|===

====

.单元格跨三列合并居中
====

    3+^|举例

|===
|a|b|c
3+^|举例
|===

====

.单元格跨两行合并
====

    .2+.^|举例

|===
.2+.^|举例|举例
|举例
|===

====

.单元格跨行列合并
====

    |===
    |a|b|c|d
    |a 2.2+^.^|举例|d
    |a|d
    |a|b|c|d
    |===

|===
|a|b|c|d
|a 2.2+^.^|举例|d
|a|d
|a|b|c|d
|===

====

.带有源代码样式的单元格
====

|===
|java|python

a|
[source,java]
----
public class Main{
    int a = 0;
}
----
a|
[source,python]
----
import os
print ("%s" %(os.uname()))
----
|===

====

=== 表头和页脚

可以通过将 `footer` 或 `header` 关键字添加到 `option` 属性中使得表格最后一行作为页脚或首行作为表头

    [options="footer,header"]

=== 表格宽度

默认情况下表格使用内容区域的宽度, 要限制表格的宽度, 需要在 `width` 属性中设置, 宽度是1-100的百分比正数

==== 自定义宽度

    [width=50%]

[width=50%]
|===
3*|a
|===

==== 使用自动宽度

    [width=%autowidth]

=== 表格边框

==== frame

表格边框是由 `frame` 属性控制的, 默认值为 `all` , 表示全边框, 其他可选值有 `topbot`, `sides` 或 `none`

....
[frame=topbot] 顶部和底部
[frame=sides] 左侧和右侧
[frame=none] 无边框
....

==== grid

单元格之间的边框是由 `grid` 属性控制的, 默认值为 `all`, 可选值有 `rows`, `cols`, `none`

=== 行高亮

可以使用 `stripes` 属性为单个表加上条纹, 也可以作为文档属性使用. +
`stripes` 属性接受以下值:

* none 不做处理
* even 偶数行
* odd 奇数行
* all 所有
* hover 鼠标悬停

=== 分隔符和数据表

默认的分割符为 `|`, 可以通过 `separator` 属性来改变分割符, 例如 `[separator=:]`.

数据表不支持跨行跨列,格式可以由 `format` 来指定,常用格式有 `csv=,`, `tsv=制表符`,`dsv=:`.

表格的缩写:

* `csv` : `,===`
* `dsv` : `:===`

== 网址
